// import the library
import { library } from '@fortawesome/fontawesome-svg-core';

// import your icons
import {
  faCode,
  faHighlighter,
  faHome,
  faPlay,
  faShoppingCart,
  faPeopleCarry,
  faPager,
  faPersonBooth,
  faUserCircle,
  faInfo,
  faComment,
  faCommentAlt,
  faInfoCircle,
  faShoppingBasket,
  faCaretRight,
  faCaretLeft,
  faBars,
  faTrash,
  faSpinner,
  faPlusCircle,
  faEdit,
  faList,
  faHeart,
  faPlus,
  faMinus,
} from '@fortawesome/free-solid-svg-icons';

// add icons to your working library/

library.add(
  faCode,
  faHighlighter,
  faHome,
  faPlay,
  faShoppingCart,
  faPeopleCarry,
  faPager,
  faPersonBooth,
  faUserCircle,
  faInfo,
  faComment,
  faCommentAlt,
  faInfoCircle,
  faShoppingBasket,
  faCaretRight,
  faCaretLeft,
  faBars,
  faTrash,
  faSpinner,
  faPlusCircle,
  faEdit,
  faList,
  faHeart,
  faPlus,
  faMinus,
);
